# Generated by Django 4.2.6 on 2023-10-22 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField(blank=True, default='1000', null=True)),
                ('image', models.ImageField(upload_to='assets\\img\\poducts')),
                ('drug_interactions', models.CharField(blank=True, max_length=10000, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cannot_be_added', models.BooleanField(default=False)),
                ('buy_from_avalable', models.IntegerField(blank=True, null=True)),
                ('avalable', models.IntegerField(blank=True, null=True)),
                ('selected_medicines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_medicines', to='medicine.medicine')),
            ],
        ),
    ]
