# Generated by Django 4.2.3 on 2023-10-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.IntegerField(default='1000', verbose_name='فیلد تداخل دارویی اجباری'),
        ),
    ]
